version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflare-tunnel.yml:/etc/cloudflared/config.yml
      - cloudflared-data:/etc/cloudflared
    networks:
      - supabase_default

volumes:
  cloudflared-data:

networks:
  supabase_default:
    external: true